FROM node:11.12.0-alpine

# https://www.npmjs.com/package/db-migrate
# https://db-migrate.readthedocs.io/en/latest/Getting%20Started/installation/
# DB MIGRATION
RUN npm i -g db-migrate
RUN npm i -g db-migrate-mysql

# https://gruntjs.com/
# TASK RUNNER
RUN npm i -g grunt